# Generated by Django 3.2.8 on 2021-10-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Name')),
                ('project_describe', models.TextField(verbose_name='Describe')),
                ('project_link', models.CharField(max_length=2050, verbose_name='Link')),
                ('project_published', models.DateTimeField(auto_now=True, verbose_name='Published')),
            ],
        ),
    ]
